package com.study.foundation.dao.model;

public class All {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_all.id
     *
     * @mbg.generated Fri Nov 22 18:43:49 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_all.name
     *
     * @mbg.generated Fri Nov 22 18:43:49 CST 2019
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_all.id
     *
     * @return the value of t_all.id
     *
     * @mbg.generated Fri Nov 22 18:43:49 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_all.id
     *
     * @param id the value for t_all.id
     *
     * @mbg.generated Fri Nov 22 18:43:49 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_all.name
     *
     * @return the value of t_all.name
     *
     * @mbg.generated Fri Nov 22 18:43:49 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_all.name
     *
     * @param name the value for t_all.name
     *
     * @mbg.generated Fri Nov 22 18:43:49 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}