package com.study.foundation.dao.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class MythOrderServiceExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table myth_order_service
     *
     * @mbg.generated Mon Apr 29 15:56:37 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table myth_order_service
     *
     * @mbg.generated Mon Apr 29 15:56:37 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table myth_order_service
     *
     * @mbg.generated Mon Apr 29 15:56:37 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myth_order_service
     *
     * @mbg.generated Mon Apr 29 15:56:37 CST 2019
     */
    public MythOrderServiceExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myth_order_service
     *
     * @mbg.generated Mon Apr 29 15:56:37 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myth_order_service
     *
     * @mbg.generated Mon Apr 29 15:56:37 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myth_order_service
     *
     * @mbg.generated Mon Apr 29 15:56:37 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myth_order_service
     *
     * @mbg.generated Mon Apr 29 15:56:37 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myth_order_service
     *
     * @mbg.generated Mon Apr 29 15:56:37 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myth_order_service
     *
     * @mbg.generated Mon Apr 29 15:56:37 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myth_order_service
     *
     * @mbg.generated Mon Apr 29 15:56:37 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myth_order_service
     *
     * @mbg.generated Mon Apr 29 15:56:37 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myth_order_service
     *
     * @mbg.generated Mon Apr 29 15:56:37 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myth_order_service
     *
     * @mbg.generated Mon Apr 29 15:56:37 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table myth_order_service
     *
     * @mbg.generated Mon Apr 29 15:56:37 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andTransIdIsNull() {
            addCriterion("trans_id is null");
            return (Criteria) this;
        }

        public Criteria andTransIdIsNotNull() {
            addCriterion("trans_id is not null");
            return (Criteria) this;
        }

        public Criteria andTransIdEqualTo(String value) {
            addCriterion("trans_id =", value, "transId");
            return (Criteria) this;
        }

        public Criteria andTransIdNotEqualTo(String value) {
            addCriterion("trans_id <>", value, "transId");
            return (Criteria) this;
        }

        public Criteria andTransIdGreaterThan(String value) {
            addCriterion("trans_id >", value, "transId");
            return (Criteria) this;
        }

        public Criteria andTransIdGreaterThanOrEqualTo(String value) {
            addCriterion("trans_id >=", value, "transId");
            return (Criteria) this;
        }

        public Criteria andTransIdLessThan(String value) {
            addCriterion("trans_id <", value, "transId");
            return (Criteria) this;
        }

        public Criteria andTransIdLessThanOrEqualTo(String value) {
            addCriterion("trans_id <=", value, "transId");
            return (Criteria) this;
        }

        public Criteria andTransIdLike(String value) {
            addCriterion("trans_id like", value, "transId");
            return (Criteria) this;
        }

        public Criteria andTransIdNotLike(String value) {
            addCriterion("trans_id not like", value, "transId");
            return (Criteria) this;
        }

        public Criteria andTransIdIn(List<String> values) {
            addCriterion("trans_id in", values, "transId");
            return (Criteria) this;
        }

        public Criteria andTransIdNotIn(List<String> values) {
            addCriterion("trans_id not in", values, "transId");
            return (Criteria) this;
        }

        public Criteria andTransIdBetween(String value1, String value2) {
            addCriterion("trans_id between", value1, value2, "transId");
            return (Criteria) this;
        }

        public Criteria andTransIdNotBetween(String value1, String value2) {
            addCriterion("trans_id not between", value1, value2, "transId");
            return (Criteria) this;
        }

        public Criteria andTargetClassIsNull() {
            addCriterion("target_class is null");
            return (Criteria) this;
        }

        public Criteria andTargetClassIsNotNull() {
            addCriterion("target_class is not null");
            return (Criteria) this;
        }

        public Criteria andTargetClassEqualTo(String value) {
            addCriterion("target_class =", value, "targetClass");
            return (Criteria) this;
        }

        public Criteria andTargetClassNotEqualTo(String value) {
            addCriterion("target_class <>", value, "targetClass");
            return (Criteria) this;
        }

        public Criteria andTargetClassGreaterThan(String value) {
            addCriterion("target_class >", value, "targetClass");
            return (Criteria) this;
        }

        public Criteria andTargetClassGreaterThanOrEqualTo(String value) {
            addCriterion("target_class >=", value, "targetClass");
            return (Criteria) this;
        }

        public Criteria andTargetClassLessThan(String value) {
            addCriterion("target_class <", value, "targetClass");
            return (Criteria) this;
        }

        public Criteria andTargetClassLessThanOrEqualTo(String value) {
            addCriterion("target_class <=", value, "targetClass");
            return (Criteria) this;
        }

        public Criteria andTargetClassLike(String value) {
            addCriterion("target_class like", value, "targetClass");
            return (Criteria) this;
        }

        public Criteria andTargetClassNotLike(String value) {
            addCriterion("target_class not like", value, "targetClass");
            return (Criteria) this;
        }

        public Criteria andTargetClassIn(List<String> values) {
            addCriterion("target_class in", values, "targetClass");
            return (Criteria) this;
        }

        public Criteria andTargetClassNotIn(List<String> values) {
            addCriterion("target_class not in", values, "targetClass");
            return (Criteria) this;
        }

        public Criteria andTargetClassBetween(String value1, String value2) {
            addCriterion("target_class between", value1, value2, "targetClass");
            return (Criteria) this;
        }

        public Criteria andTargetClassNotBetween(String value1, String value2) {
            addCriterion("target_class not between", value1, value2, "targetClass");
            return (Criteria) this;
        }

        public Criteria andTargetMethodIsNull() {
            addCriterion("target_method is null");
            return (Criteria) this;
        }

        public Criteria andTargetMethodIsNotNull() {
            addCriterion("target_method is not null");
            return (Criteria) this;
        }

        public Criteria andTargetMethodEqualTo(String value) {
            addCriterion("target_method =", value, "targetMethod");
            return (Criteria) this;
        }

        public Criteria andTargetMethodNotEqualTo(String value) {
            addCriterion("target_method <>", value, "targetMethod");
            return (Criteria) this;
        }

        public Criteria andTargetMethodGreaterThan(String value) {
            addCriterion("target_method >", value, "targetMethod");
            return (Criteria) this;
        }

        public Criteria andTargetMethodGreaterThanOrEqualTo(String value) {
            addCriterion("target_method >=", value, "targetMethod");
            return (Criteria) this;
        }

        public Criteria andTargetMethodLessThan(String value) {
            addCriterion("target_method <", value, "targetMethod");
            return (Criteria) this;
        }

        public Criteria andTargetMethodLessThanOrEqualTo(String value) {
            addCriterion("target_method <=", value, "targetMethod");
            return (Criteria) this;
        }

        public Criteria andTargetMethodLike(String value) {
            addCriterion("target_method like", value, "targetMethod");
            return (Criteria) this;
        }

        public Criteria andTargetMethodNotLike(String value) {
            addCriterion("target_method not like", value, "targetMethod");
            return (Criteria) this;
        }

        public Criteria andTargetMethodIn(List<String> values) {
            addCriterion("target_method in", values, "targetMethod");
            return (Criteria) this;
        }

        public Criteria andTargetMethodNotIn(List<String> values) {
            addCriterion("target_method not in", values, "targetMethod");
            return (Criteria) this;
        }

        public Criteria andTargetMethodBetween(String value1, String value2) {
            addCriterion("target_method between", value1, value2, "targetMethod");
            return (Criteria) this;
        }

        public Criteria andTargetMethodNotBetween(String value1, String value2) {
            addCriterion("target_method not between", value1, value2, "targetMethod");
            return (Criteria) this;
        }

        public Criteria andRetriedCountIsNull() {
            addCriterion("retried_count is null");
            return (Criteria) this;
        }

        public Criteria andRetriedCountIsNotNull() {
            addCriterion("retried_count is not null");
            return (Criteria) this;
        }

        public Criteria andRetriedCountEqualTo(Integer value) {
            addCriterion("retried_count =", value, "retriedCount");
            return (Criteria) this;
        }

        public Criteria andRetriedCountNotEqualTo(Integer value) {
            addCriterion("retried_count <>", value, "retriedCount");
            return (Criteria) this;
        }

        public Criteria andRetriedCountGreaterThan(Integer value) {
            addCriterion("retried_count >", value, "retriedCount");
            return (Criteria) this;
        }

        public Criteria andRetriedCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("retried_count >=", value, "retriedCount");
            return (Criteria) this;
        }

        public Criteria andRetriedCountLessThan(Integer value) {
            addCriterion("retried_count <", value, "retriedCount");
            return (Criteria) this;
        }

        public Criteria andRetriedCountLessThanOrEqualTo(Integer value) {
            addCriterion("retried_count <=", value, "retriedCount");
            return (Criteria) this;
        }

        public Criteria andRetriedCountIn(List<Integer> values) {
            addCriterion("retried_count in", values, "retriedCount");
            return (Criteria) this;
        }

        public Criteria andRetriedCountNotIn(List<Integer> values) {
            addCriterion("retried_count not in", values, "retriedCount");
            return (Criteria) this;
        }

        public Criteria andRetriedCountBetween(Integer value1, Integer value2) {
            addCriterion("retried_count between", value1, value2, "retriedCount");
            return (Criteria) this;
        }

        public Criteria andRetriedCountNotBetween(Integer value1, Integer value2) {
            addCriterion("retried_count not between", value1, value2, "retriedCount");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andLastTimeIsNull() {
            addCriterion("last_time is null");
            return (Criteria) this;
        }

        public Criteria andLastTimeIsNotNull() {
            addCriterion("last_time is not null");
            return (Criteria) this;
        }

        public Criteria andLastTimeEqualTo(Date value) {
            addCriterion("last_time =", value, "lastTime");
            return (Criteria) this;
        }

        public Criteria andLastTimeNotEqualTo(Date value) {
            addCriterion("last_time <>", value, "lastTime");
            return (Criteria) this;
        }

        public Criteria andLastTimeGreaterThan(Date value) {
            addCriterion("last_time >", value, "lastTime");
            return (Criteria) this;
        }

        public Criteria andLastTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("last_time >=", value, "lastTime");
            return (Criteria) this;
        }

        public Criteria andLastTimeLessThan(Date value) {
            addCriterion("last_time <", value, "lastTime");
            return (Criteria) this;
        }

        public Criteria andLastTimeLessThanOrEqualTo(Date value) {
            addCriterion("last_time <=", value, "lastTime");
            return (Criteria) this;
        }

        public Criteria andLastTimeIn(List<Date> values) {
            addCriterion("last_time in", values, "lastTime");
            return (Criteria) this;
        }

        public Criteria andLastTimeNotIn(List<Date> values) {
            addCriterion("last_time not in", values, "lastTime");
            return (Criteria) this;
        }

        public Criteria andLastTimeBetween(Date value1, Date value2) {
            addCriterion("last_time between", value1, value2, "lastTime");
            return (Criteria) this;
        }

        public Criteria andLastTimeNotBetween(Date value1, Date value2) {
            addCriterion("last_time not between", value1, value2, "lastTime");
            return (Criteria) this;
        }

        public Criteria andVersionIsNull() {
            addCriterion("version is null");
            return (Criteria) this;
        }

        public Criteria andVersionIsNotNull() {
            addCriterion("version is not null");
            return (Criteria) this;
        }

        public Criteria andVersionEqualTo(Integer value) {
            addCriterion("version =", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotEqualTo(Integer value) {
            addCriterion("version <>", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThan(Integer value) {
            addCriterion("version >", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThanOrEqualTo(Integer value) {
            addCriterion("version >=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThan(Integer value) {
            addCriterion("version <", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThanOrEqualTo(Integer value) {
            addCriterion("version <=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionIn(List<Integer> values) {
            addCriterion("version in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotIn(List<Integer> values) {
            addCriterion("version not in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionBetween(Integer value1, Integer value2) {
            addCriterion("version between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotBetween(Integer value1, Integer value2) {
            addCriterion("version not between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andRoleIsNull() {
            addCriterion("role is null");
            return (Criteria) this;
        }

        public Criteria andRoleIsNotNull() {
            addCriterion("role is not null");
            return (Criteria) this;
        }

        public Criteria andRoleEqualTo(Integer value) {
            addCriterion("role =", value, "role");
            return (Criteria) this;
        }

        public Criteria andRoleNotEqualTo(Integer value) {
            addCriterion("role <>", value, "role");
            return (Criteria) this;
        }

        public Criteria andRoleGreaterThan(Integer value) {
            addCriterion("role >", value, "role");
            return (Criteria) this;
        }

        public Criteria andRoleGreaterThanOrEqualTo(Integer value) {
            addCriterion("role >=", value, "role");
            return (Criteria) this;
        }

        public Criteria andRoleLessThan(Integer value) {
            addCriterion("role <", value, "role");
            return (Criteria) this;
        }

        public Criteria andRoleLessThanOrEqualTo(Integer value) {
            addCriterion("role <=", value, "role");
            return (Criteria) this;
        }

        public Criteria andRoleIn(List<Integer> values) {
            addCriterion("role in", values, "role");
            return (Criteria) this;
        }

        public Criteria andRoleNotIn(List<Integer> values) {
            addCriterion("role not in", values, "role");
            return (Criteria) this;
        }

        public Criteria andRoleBetween(Integer value1, Integer value2) {
            addCriterion("role between", value1, value2, "role");
            return (Criteria) this;
        }

        public Criteria andRoleNotBetween(Integer value1, Integer value2) {
            addCriterion("role not between", value1, value2, "role");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table myth_order_service
     *
     * @mbg.generated do_not_delete_during_merge Mon Apr 29 15:56:37 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table myth_order_service
     *
     * @mbg.generated Mon Apr 29 15:56:37 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}