package com.study.foundation.dao.model;

import java.util.Date;

public class MythOrderService {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myth_order_service.trans_id
     *
     * @mbg.generated Mon Apr 29 15:56:37 CST 2019
     */
    private String transId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myth_order_service.target_class
     *
     * @mbg.generated Mon Apr 29 15:56:37 CST 2019
     */
    private String targetClass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myth_order_service.target_method
     *
     * @mbg.generated Mon Apr 29 15:56:37 CST 2019
     */
    private String targetMethod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myth_order_service.retried_count
     *
     * @mbg.generated Mon Apr 29 15:56:37 CST 2019
     */
    private Integer retriedCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myth_order_service.create_time
     *
     * @mbg.generated Mon Apr 29 15:56:37 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myth_order_service.last_time
     *
     * @mbg.generated Mon Apr 29 15:56:37 CST 2019
     */
    private Date lastTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myth_order_service.version
     *
     * @mbg.generated Mon Apr 29 15:56:37 CST 2019
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myth_order_service.status
     *
     * @mbg.generated Mon Apr 29 15:56:37 CST 2019
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myth_order_service.role
     *
     * @mbg.generated Mon Apr 29 15:56:37 CST 2019
     */
    private Integer role;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myth_order_service.trans_id
     *
     * @return the value of myth_order_service.trans_id
     *
     * @mbg.generated Mon Apr 29 15:56:37 CST 2019
     */
    public String getTransId() {
        return transId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myth_order_service.trans_id
     *
     * @param transId the value for myth_order_service.trans_id
     *
     * @mbg.generated Mon Apr 29 15:56:37 CST 2019
     */
    public void setTransId(String transId) {
        this.transId = transId == null ? null : transId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myth_order_service.target_class
     *
     * @return the value of myth_order_service.target_class
     *
     * @mbg.generated Mon Apr 29 15:56:37 CST 2019
     */
    public String getTargetClass() {
        return targetClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myth_order_service.target_class
     *
     * @param targetClass the value for myth_order_service.target_class
     *
     * @mbg.generated Mon Apr 29 15:56:37 CST 2019
     */
    public void setTargetClass(String targetClass) {
        this.targetClass = targetClass == null ? null : targetClass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myth_order_service.target_method
     *
     * @return the value of myth_order_service.target_method
     *
     * @mbg.generated Mon Apr 29 15:56:37 CST 2019
     */
    public String getTargetMethod() {
        return targetMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myth_order_service.target_method
     *
     * @param targetMethod the value for myth_order_service.target_method
     *
     * @mbg.generated Mon Apr 29 15:56:37 CST 2019
     */
    public void setTargetMethod(String targetMethod) {
        this.targetMethod = targetMethod == null ? null : targetMethod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myth_order_service.retried_count
     *
     * @return the value of myth_order_service.retried_count
     *
     * @mbg.generated Mon Apr 29 15:56:37 CST 2019
     */
    public Integer getRetriedCount() {
        return retriedCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myth_order_service.retried_count
     *
     * @param retriedCount the value for myth_order_service.retried_count
     *
     * @mbg.generated Mon Apr 29 15:56:37 CST 2019
     */
    public void setRetriedCount(Integer retriedCount) {
        this.retriedCount = retriedCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myth_order_service.create_time
     *
     * @return the value of myth_order_service.create_time
     *
     * @mbg.generated Mon Apr 29 15:56:37 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myth_order_service.create_time
     *
     * @param createTime the value for myth_order_service.create_time
     *
     * @mbg.generated Mon Apr 29 15:56:37 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myth_order_service.last_time
     *
     * @return the value of myth_order_service.last_time
     *
     * @mbg.generated Mon Apr 29 15:56:37 CST 2019
     */
    public Date getLastTime() {
        return lastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myth_order_service.last_time
     *
     * @param lastTime the value for myth_order_service.last_time
     *
     * @mbg.generated Mon Apr 29 15:56:37 CST 2019
     */
    public void setLastTime(Date lastTime) {
        this.lastTime = lastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myth_order_service.version
     *
     * @return the value of myth_order_service.version
     *
     * @mbg.generated Mon Apr 29 15:56:37 CST 2019
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myth_order_service.version
     *
     * @param version the value for myth_order_service.version
     *
     * @mbg.generated Mon Apr 29 15:56:37 CST 2019
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myth_order_service.status
     *
     * @return the value of myth_order_service.status
     *
     * @mbg.generated Mon Apr 29 15:56:37 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myth_order_service.status
     *
     * @param status the value for myth_order_service.status
     *
     * @mbg.generated Mon Apr 29 15:56:37 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myth_order_service.role
     *
     * @return the value of myth_order_service.role
     *
     * @mbg.generated Mon Apr 29 15:56:37 CST 2019
     */
    public Integer getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myth_order_service.role
     *
     * @param role the value for myth_order_service.role
     *
     * @mbg.generated Mon Apr 29 15:56:37 CST 2019
     */
    public void setRole(Integer role) {
        this.role = role;
    }
}