package com.study.foundation.dao.model;

public class MythOrderServiceWithBLOBs extends MythOrderService {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myth_order_service.invocation
     *
     * @mbg.generated Mon Apr 29 15:56:37 CST 2019
     */
    private byte[] invocation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myth_order_service.error_msg
     *
     * @mbg.generated Mon Apr 29 15:56:37 CST 2019
     */
    private String errorMsg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myth_order_service.invocation
     *
     * @return the value of myth_order_service.invocation
     *
     * @mbg.generated Mon Apr 29 15:56:37 CST 2019
     */
    public byte[] getInvocation() {
        return invocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myth_order_service.invocation
     *
     * @param invocation the value for myth_order_service.invocation
     *
     * @mbg.generated Mon Apr 29 15:56:37 CST 2019
     */
    public void setInvocation(byte[] invocation) {
        this.invocation = invocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myth_order_service.error_msg
     *
     * @return the value of myth_order_service.error_msg
     *
     * @mbg.generated Mon Apr 29 15:56:37 CST 2019
     */
    public String getErrorMsg() {
        return errorMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myth_order_service.error_msg
     *
     * @param errorMsg the value for myth_order_service.error_msg
     *
     * @mbg.generated Mon Apr 29 15:56:37 CST 2019
     */
    public void setErrorMsg(String errorMsg) {
        this.errorMsg = errorMsg == null ? null : errorMsg.trim();
    }
}