package com.study.foundation.dao.model;

public class OrderItem {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_item.order_item_id
     *
     * @mbg.generated Thu Nov 21 16:05:12 CST 2019
     */
    private Long orderItemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_item.order_id
     *
     * @mbg.generated Thu Nov 21 16:05:12 CST 2019
     */
    private Long orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_item.user_id
     *
     * @mbg.generated Thu Nov 21 16:05:12 CST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_item.status
     *
     * @mbg.generated Thu Nov 21 16:05:12 CST 2019
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_item.order_item_id
     *
     * @return the value of t_order_item.order_item_id
     *
     * @mbg.generated Thu Nov 21 16:05:12 CST 2019
     */
    public Long getOrderItemId() {
        return orderItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_item.order_item_id
     *
     * @param orderItemId the value for t_order_item.order_item_id
     *
     * @mbg.generated Thu Nov 21 16:05:12 CST 2019
     */
    public void setOrderItemId(Long orderItemId) {
        this.orderItemId = orderItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_item.order_id
     *
     * @return the value of t_order_item.order_id
     *
     * @mbg.generated Thu Nov 21 16:05:12 CST 2019
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_item.order_id
     *
     * @param orderId the value for t_order_item.order_id
     *
     * @mbg.generated Thu Nov 21 16:05:12 CST 2019
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_item.user_id
     *
     * @return the value of t_order_item.user_id
     *
     * @mbg.generated Thu Nov 21 16:05:12 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_item.user_id
     *
     * @param userId the value for t_order_item.user_id
     *
     * @mbg.generated Thu Nov 21 16:05:12 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_item.status
     *
     * @return the value of t_order_item.status
     *
     * @mbg.generated Thu Nov 21 16:05:12 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_item.status
     *
     * @param status the value for t_order_item.status
     *
     * @mbg.generated Thu Nov 21 16:05:12 CST 2019
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}