package com.study.foundation.dao.model;

import java.util.Date;

public class TimeSharding {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_time_sharding_0.id
     *
     * @mbg.generated Fri Nov 22 19:04:51 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_time_sharding_0.create_time
     *
     * @mbg.generated Fri Nov 22 19:04:51 CST 2019
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_time_sharding_0.id
     *
     * @return the value of t_time_sharding_0.id
     *
     * @mbg.generated Fri Nov 22 19:04:51 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_time_sharding_0.id
     *
     * @param id the value for t_time_sharding_0.id
     *
     * @mbg.generated Fri Nov 22 19:04:51 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_time_sharding_0.create_time
     *
     * @return the value of t_time_sharding_0.create_time
     *
     * @mbg.generated Fri Nov 22 19:04:51 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_time_sharding_0.create_time
     *
     * @param createTime the value for t_time_sharding_0.create_time
     *
     * @mbg.generated Fri Nov 22 19:04:51 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}