package com.study.foundation.dao.mapper;

import com.study.foundation.dao.model.All;
import com.study.foundation.dao.model.AllExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AllMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_all
     *
     * @mbg.generated Fri Nov 22 18:43:49 CST 2019
     */
    long countByExample(AllExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_all
     *
     * @mbg.generated Fri Nov 22 18:43:49 CST 2019
     */
    int deleteByExample(AllExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_all
     *
     * @mbg.generated Fri Nov 22 18:43:49 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_all
     *
     * @mbg.generated Fri Nov 22 18:43:49 CST 2019
     */
    int insert(All record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_all
     *
     * @mbg.generated Fri Nov 22 18:43:49 CST 2019
     */
    int insertSelective(All record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_all
     *
     * @mbg.generated Fri Nov 22 18:43:49 CST 2019
     */
    List<All> selectByExample(AllExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_all
     *
     * @mbg.generated Fri Nov 22 18:43:49 CST 2019
     */
    All selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_all
     *
     * @mbg.generated Fri Nov 22 18:43:49 CST 2019
     */
    int updateByExampleSelective(@Param("record") All record, @Param("example") AllExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_all
     *
     * @mbg.generated Fri Nov 22 18:43:49 CST 2019
     */
    int updateByExample(@Param("record") All record, @Param("example") AllExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_all
     *
     * @mbg.generated Fri Nov 22 18:43:49 CST 2019
     */
    int updateByPrimaryKeySelective(All record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_all
     *
     * @mbg.generated Fri Nov 22 18:43:49 CST 2019
     */
    int updateByPrimaryKey(All record);
}