package com.study.foundation.dao.mapper;

import com.study.foundation.dao.model.MythOrderService;
import com.study.foundation.dao.model.MythOrderServiceExample;
import com.study.foundation.dao.model.MythOrderServiceWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MythOrderServiceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myth_order_service
     *
     * @mbg.generated Mon Apr 29 15:56:37 CST 2019
     */
    long countByExample(MythOrderServiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myth_order_service
     *
     * @mbg.generated Mon Apr 29 15:56:37 CST 2019
     */
    int deleteByExample(MythOrderServiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myth_order_service
     *
     * @mbg.generated Mon Apr 29 15:56:37 CST 2019
     */
    int deleteByPrimaryKey(String transId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myth_order_service
     *
     * @mbg.generated Mon Apr 29 15:56:37 CST 2019
     */
    int insert(MythOrderServiceWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myth_order_service
     *
     * @mbg.generated Mon Apr 29 15:56:37 CST 2019
     */
    int insertSelective(MythOrderServiceWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myth_order_service
     *
     * @mbg.generated Mon Apr 29 15:56:37 CST 2019
     */
    List<MythOrderServiceWithBLOBs> selectByExampleWithBLOBs(MythOrderServiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myth_order_service
     *
     * @mbg.generated Mon Apr 29 15:56:37 CST 2019
     */
    List<MythOrderService> selectByExample(MythOrderServiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myth_order_service
     *
     * @mbg.generated Mon Apr 29 15:56:37 CST 2019
     */
    MythOrderServiceWithBLOBs selectByPrimaryKey(String transId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myth_order_service
     *
     * @mbg.generated Mon Apr 29 15:56:37 CST 2019
     */
    int updateByExampleSelective(@Param("record") MythOrderServiceWithBLOBs record, @Param("example") MythOrderServiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myth_order_service
     *
     * @mbg.generated Mon Apr 29 15:56:37 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") MythOrderServiceWithBLOBs record, @Param("example") MythOrderServiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myth_order_service
     *
     * @mbg.generated Mon Apr 29 15:56:37 CST 2019
     */
    int updateByExample(@Param("record") MythOrderService record, @Param("example") MythOrderServiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myth_order_service
     *
     * @mbg.generated Mon Apr 29 15:56:37 CST 2019
     */
    int updateByPrimaryKeySelective(MythOrderServiceWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myth_order_service
     *
     * @mbg.generated Mon Apr 29 15:56:37 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(MythOrderServiceWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myth_order_service
     *
     * @mbg.generated Mon Apr 29 15:56:37 CST 2019
     */
    int updateByPrimaryKey(MythOrderService record);
}