package com.study.foundation.dao.mapper;

import com.study.foundation.dao.model.NormalTable;
import com.study.foundation.dao.model.NormalTableExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NormalTableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_normal_table
     *
     * @mbg.generated Mon Nov 25 12:29:08 CST 2019
     */
    long countByExample(NormalTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_normal_table
     *
     * @mbg.generated Mon Nov 25 12:29:08 CST 2019
     */
    int deleteByExample(NormalTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_normal_table
     *
     * @mbg.generated Mon Nov 25 12:29:08 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_normal_table
     *
     * @mbg.generated Mon Nov 25 12:29:08 CST 2019
     */
    int insert(NormalTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_normal_table
     *
     * @mbg.generated Mon Nov 25 12:29:08 CST 2019
     */
    int insertSelective(NormalTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_normal_table
     *
     * @mbg.generated Mon Nov 25 12:29:08 CST 2019
     */
    List<NormalTable> selectByExample(NormalTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_normal_table
     *
     * @mbg.generated Mon Nov 25 12:29:08 CST 2019
     */
    NormalTable selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_normal_table
     *
     * @mbg.generated Mon Nov 25 12:29:08 CST 2019
     */
    int updateByExampleSelective(@Param("record") NormalTable record, @Param("example") NormalTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_normal_table
     *
     * @mbg.generated Mon Nov 25 12:29:08 CST 2019
     */
    int updateByExample(@Param("record") NormalTable record, @Param("example") NormalTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_normal_table
     *
     * @mbg.generated Mon Nov 25 12:29:08 CST 2019
     */
    int updateByPrimaryKeySelective(NormalTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_normal_table
     *
     * @mbg.generated Mon Nov 25 12:29:08 CST 2019
     */
    int updateByPrimaryKey(NormalTable record);
}