package com.study.foundation.dao.mapper;

import com.study.foundation.dao.model.TimeSharding;
import com.study.foundation.dao.model.TimeShardingExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TimeShardingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_time_sharding_0
     *
     * @mbg.generated Fri Nov 22 19:04:51 CST 2019
     */
    long countByExample(TimeShardingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_time_sharding_0
     *
     * @mbg.generated Fri Nov 22 19:04:51 CST 2019
     */
    int deleteByExample(TimeShardingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_time_sharding_0
     *
     * @mbg.generated Fri Nov 22 19:04:51 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_time_sharding_0
     *
     * @mbg.generated Fri Nov 22 19:04:51 CST 2019
     */
    int insert(TimeSharding record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_time_sharding_0
     *
     * @mbg.generated Fri Nov 22 19:04:51 CST 2019
     */
    int insertSelective(TimeSharding record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_time_sharding_0
     *
     * @mbg.generated Fri Nov 22 19:04:51 CST 2019
     */
    List<TimeSharding> selectByExample(TimeShardingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_time_sharding_0
     *
     * @mbg.generated Fri Nov 22 19:04:51 CST 2019
     */
    TimeSharding selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_time_sharding_0
     *
     * @mbg.generated Fri Nov 22 19:04:51 CST 2019
     */
    int updateByExampleSelective(@Param("record") TimeSharding record, @Param("example") TimeShardingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_time_sharding_0
     *
     * @mbg.generated Fri Nov 22 19:04:51 CST 2019
     */
    int updateByExample(@Param("record") TimeSharding record, @Param("example") TimeShardingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_time_sharding_0
     *
     * @mbg.generated Fri Nov 22 19:04:51 CST 2019
     */
    int updateByPrimaryKeySelective(TimeSharding record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_time_sharding_0
     *
     * @mbg.generated Fri Nov 22 19:04:51 CST 2019
     */
    int updateByPrimaryKey(TimeSharding record);
}